services:
  - type: web
    name: EventMaster1
    runtime: python:
               version: 3.11.6
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn main:app --worker-class uvicorn.workers.UvicornWorker --workers 4 --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: urfutable
          property: connectionString
      - key: SECRET_KEY
        value: d2Flf93!kL_42$%k2Qz1@fkEjd*daP2
      - key: MAILRU_CLIENT_ID
        value: 890ea7b9c21d4fe98aeccd1a457dc9fc
      - key: MAILRU_CLIENT_SECRET
        value: 19ef2f3739f1461d9adc5894ecfc0f13
