services:
  - type: web
    name: EventMaster1
    runtime: python
    python:
      version: "3.11.7"
    buildCommand: |
      python -m pip install --upgrade pip
      pip install setuptools==65.5.1 wheel
      pip install -r requirements.txt
    startCommand: |
      PORT=${PORT:-8000}
      uvicorn main:app --host 0.0.0.0 --port $PORT --workers 4
    envVars:
      - key: APP_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://mrx:2IAsjs5oOfdEgB2pacpqdPZbhaMOmFN1@dpg-d1aj6jmmcj7s73fjkdu0-a/urfutable
        fromDatabase:
          name: urfutable
          property: connectionString
      - key: PYTHONUNBUFFERED
        value: 1
      - key: SECRET_KEY
        value: d2Flf93!kL_42$%k2Qz1@fkEjd*daP2
      - key: MAILRU_CLIENT_ID
        value: 890ea7b9c21d4fe98aeccd1a457dc9fc
      - key: MAILRU_CLIENT_SECRET
        value: 19ef2f3739f1461d9adc5894ecfc0f13
